source "https://rubygems.org"

if Gem.win_platform?
  gem "tzinfo-data"
  gem "wdm", "~> 0.1.0"
end

if ENV["JEKYLL_VERSION"]
  gem "jekyll", ENV["JEKYLL_VERSION"]
else
  gem "jekyll", github: "jekyll/jekyll"
end

gem "memory_profiler"
gem "jekyll-data", github: "ashmaroli/jekyll-data", branch: "trials"

if ENV["MMISTAKES_EDGE"]
  gem "minimal-mistakes-jekyll", github: "ashmaroli/minimal-mistakes", branch: "memory-profile"
else
  gem "minimal-mistakes-jekyll", github: "ashmaroli/minimal-mistakes", branch: "master"
end

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "jekyll-gist"
  gem "jekyll-feed"
  gem "jemoji"
  gem "jekyll-include-cache"
  # gem "jekyll-algolia"
end
